### ISSUE TITLE
Troubleshoot stuck "Firing..." state on both watch and iOS apps

### ISSUE THREAD

**Issue by robertoandrade** [octoblu/blu-ios#5]
Some users are reporting that both apps show a trigger in the "Firing..." state and it gets stuck there without feedback.

One way I found to reproducing this is if the watch loses connectivity with the phone, ie: if you close the iPhone simulator after having launched the watch app and trying to tap a trigger to launch it.

It looks like there are similar reports of it happening on the phone also? I noticed that if  the firing request fails it doesn't not update the UI either.

**Comment by peterdemartini** [comment]
I deployed a fix to the triggers-service which fixed the trigger response error and it not changing from fired!

**Comment by robertoandrade** [comment]
I'm guessing a way to repro the second issue would be to change the URL for the trigger service so the requests always fail to see if the UI indicates the failure accordingly.

Will take a look at these issues tomorrow and let you guys know.
